### PR TITLE
Change the base Docker image

### PR DESCRIPTION
**Pull request by waisbrot**
Use the official python:2.7-alpine image for the same environment but
a slightly better build (faster to build the image, clearer what version
of Python's in there).

### CODE REVIEW

**Comment by tjcorr** [comment]
I like the idea of utilizing the official python image. However when I went to compare the final images I noticed we gained quite a bit of bloat:

etcd-aws-cluster                              python              f92e3afddd90        4 seconds ago        **114.8 MB**
etcd-aws-cluster                              master              eed190f30e5d        About a minute ago   **89.27 MB**

I'm wondering if the larger resulting file size is worth it. Perhaps we could just add a build trigger to rebuild whenever the official python repo is updated to help make sure we stay up-to-date?

**Comment by waisbrot** [comment]
Yes, I can see why: the official Python-Alpine image includes many more libraries to support Python programs in general. https://github.com/docker-library/python/blob/855b85c8309e925814dfa97d61310080dcd08db6/2.7/alpine/Dockerfile

There's no python-slim-alpine, but that seems like what you'd want here.

In general, I've gotten a lot more space-saving out of using a (rather bloated) common base image with a few source files on top than I have from building very slim individual images. I'm not offended if you disagree, though 🙂. 

I'm actually working on rewriting this as a boto3 script because I'd like to perform some additional AWS actions (DNS registration). I'll make another PR to show, after I've gotten it working.

**Comment by placydo** [comment]
@waisbrot have You manage to rewrite it to Boto3? Any eta?

**Comment by waisbrot** [comment]
Closing to tidy my PR history.

**Pull request closed without merging**
