### PR TITLE
Add quotes around asg_name variable

### PR DESCRIPTION
**Pull request by thomaspeitz**

### CODE REVIEW

**Comment by tjcorr** [comment]
Looks like we might need to change https://github.com/tsupertramp/etcd-aws-cluster/blob/fix-autoscaling-groups-with-spaces/etcd-aws-cluster#L156 as well.

**Comment by thomaspeitz** [comment]
Thanks - Updated the Pull Request. If you want I can create a new one for "clean" git commit message history.

**Comment by tjcorr** [comment]
Sure might as well squash it down. I spun up my test cloudformation template and everything looked fine.  I wasn't able to replicate the spaces due to limitations imposed by CloudFormation but I'm confident your change should work just fine.

**Comment by pmoust** [comment]
Even being obvious just by reading the diff, I confirm that it does work with spaced asg names.

**Comment by tjcorr** [comment]
@tsupertramp any reason you closed this?

**Comment by thomaspeitz** [comment]
Yeah i made a new one :) fixed everything in one commit (as it is cleaner)
https://github.com/MonsantoCo/etcd-aws-cluster/pull/21

**Comment by tjcorr** [comment]
ah gotcha

**Pull request closed without merging**
